const Router = require('express')
const router = new Router()

const userRouter = require('./user')
const adminRouter = require('./admin')
const pacientRouter = require('./pacient')
const vrachRouter = require('./vrach')
const analiziRouter = require('./analizi')
const raspisanieRouter = require('./raspisanie')
const dolznostRouter = require('./dolzntost')
const otdelenieRouter = require('./otdelenie')
const medRouter = require('./med_karta')
const ulicaRouter = require('./ulica')
const gorodRouter = require('./gorod')
const mesto_jitelstvaRouter = require('./mesto_jitelstva')
const zapicRouter = require('./zapic')
const priemRouter = require('./priem')
const diagnozRouter = require('./diagnos')
const preparatRouter = require('./preparat')
const plataRouter = require('./plata')
const plata_pacientRouter = require('./plata_pacient')
const diagnosis_kartRouter = require('./diagnosis_kart')
const preparat_diagnosesRouter = require('./preparat_diagnoses')
const analizi_kart_zapicRouter = require('./analizi_kart_zapic')
const diagnoz_priemRouter = require('./diagnoz_priem')


router.use('/pacient', pacientRouter)
router.use('/admin', adminRouter)
router.use('/vrach', vrachRouter)
router.use('/user', userRouter)
router.use('/analizi', analiziRouter)
router.use('/raspisanie', raspisanieRouter)
router.use('/dolznost', dolznostRouter)
router.use('/otdelenie', otdelenieRouter)
router.use('/kart', medRouter)
router.use('/ulica', ulicaRouter)
router.use('/gorod', gorodRouter)
router.use('/adress', mesto_jitelstvaRouter)
router.use('/zapic', zapicRouter)
router.use('/priem', priemRouter)
router.use('/diagnoz', diagnozRouter)
router.use('/preparat', preparatRouter)
router.use('/plata', plataRouter)
router.use('/plata_pacient', plata_pacientRouter)
router.use('/diagnosis_kart', diagnosis_kartRouter)
router.use('/preparat_diagnoses', preparat_diagnosesRouter)
router.use('/analizi_kart_zapic', analizi_kart_zapicRouter)
router.use('/diagnoz_priem', diagnoz_priemRouter)

module.exports = router